Cli
Proyecto-Vegeta/torneo pull request #6
Opened 2022-07-29 02:09 UTC by Negroraton

2022-08-01 21:42 UTC, manquius requested changes

2022-08-01 21:42 UTC, manquius commented on src/main/java/com/vegeta/Main.java
> +        do {
Pondria todo el do {}while() en una funcion que se llame menuPrincipal()

2022-08-01 21:42 UTC, manquius commented on src/main/java/com/vegeta/Main.java
> +        if (parseInt(opcion)==1) {
Pondría todo el if con su contenido en un metodo que se llame nuevoLuchador

2022-08-02 02:09 UTC, LeoTheEvil commented on src/main/java/com/vegeta/Main.java
> +        do {
"Funcion" quiere decir Clase o Metodo en este contexto?

2022-08-02 02:13 UTC, LeoTheEvil commented on src/main/java/com/vegeta/Main.java
> +        if (parseInt(opcion)==1) {
TODO el if? No seria mejor...?

if (parseInt(opcion)==1) {
            nuevoLuchador();
        }
    }

    public void nuevoLuchador() {
        String nombre = cli.preguntar("Nombre del luchador:", new Validador());
        torneo.nuevoLuchador(nombre);
        cli.imprimir("Nuevo luchador:" + torneo.getLuchador(nombre).getNombre());
    }

2022-08-02 12:23 UTC, fermancuso commented on src/main/java/com/vegeta/Main.java
> +        do {
Funcion es Metodo

2022-08-02 12:24 UTC, fermancuso commented on src/main/java/com/vegeta/Main.java
> +        if (parseInt(opcion)==1) {
el nuevo luchador se crearia si eligio la opcion 1.... deberia llamarse de otra forma si tambien incluis el if.

2022-08-02 23:27 UTC, manquius approved these changes

2022-08-02 23:27 UTC, merged